# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
[[ -f ~/.bashrc ]] && . ~/.bashrc
PATH="/usr/lib/ccache/bin:/opt/bin:${PATH}"
[ ! -d /tmp/thumbnails ] && [[ $(tty) = "/dev/tty1" ]] && exec startx
[[ $(tty) = "/dev/tty2" ]] && exec fbterm
